# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "337348a5ac1bad612c8f34b3d8bcc60e"
name = "HiClarify Dev"
application_url = "https://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://localhost3000/api/auth/callback" ]
