"use client";

import React, { useState, useCallback, useMemo, useEffect } from "react";
import { computeHealthScores, getHealthBanner } from "@/system-control/health-model";
import { getScanCategories, getSafetyZones } from "@/system-control/scan-interpreter";
import { getPrioritySuggestions, getMiniRefactorPlans } from "@/system-control/refactor-planner";
import {
  buildRefactorProposal,
  buildCursorCommandFromProposal,
  buildTaskFileFromProposal,
} from "@/system-control/proposal-builder";
import {
  SCAN_MODULES,
  selectedSubOptionsToApiOptions,
  fullScanApiOptions,
  getAllSubOptionIds,
  type ScanOptionKey,
} from "@/system-control/scan-modules";
import {
  computeStabilityScores,
  overallHealthScore,
  getDriftSeverity,
  getRefactorUrgency,
} from "@/system-control/stability-scoring";
import { consolidatePlans } from "@/system-control/plan-consolidation";
import { loadControlState, saveAfterScan, savePlanSelection } from "@/system-control/persistence";
import type { SystemScanResult } from "@/system-control/types";

const SCAN_OPTIONS: { key: ScanOptionKey; label: string }[] = [
  { key: "scanEngines", label: "Scan Engines" },
  { key: "scanRuntime", label: "Scan Runtime" },
  { key: "scanUIBlocks", label: "Scan UI Blocks" },
  { key: "scanRegistries", label: "Scan Registries" },
  { key: "scanApps", label: "Scan Apps" },
  { key: "scanPaths", label: "Scan Paths" },
  { key: "scanJsonDefinitions", label: "Scan JSON Definitions" },
  { key: "scanImports", label: "Scan Imports" },
  { key: "scanUnusedFiles", label: "Scan Unused Files" },
];

const SECTION_IDS = [
  "systemStructure",
  "engines",
  "blocks",
  "registries",
  "runtime",
  "apps",
  "pathHealth",
] as const;

const styles = {
  page: {
    minHeight: "100vh",
    background: "#0f172a",
    color: "#e2e8f0",
    padding: 24,
    fontFamily: "system-ui, sans-serif",
  },
  topBar: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 16,
    padding: 16,
    background: "#1e293b",
    borderRadius: 8,
    marginBottom: 24,
    border: "1px solid #334155",
  },
  stat: {
    padding: "4px 10px",
    background: "#334155",
    borderRadius: 6,
    fontSize: 13,
  },
  section: {
    marginBottom: 12,
    background: "#1e293b",
    borderRadius: 8,
    border: "1px solid #334155",
    overflow: "hidden" as const,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    cursor: "pointer" as const,
    fontWeight: 600,
    fontSize: 15,
  },
  sectionBody: {
    padding: "0 16px 16px",
    borderTop: "1px solid #334155",
  },
  checkboxRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 12,
    alignItems: "center",
    marginBottom: 16,
  },
  button: {
    padding: "10px 18px",
    background: "#3b82f6",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    cursor: "pointer" as const,
    fontWeight: 600,
    fontSize: 14,
  },
  buttonSecondary: {
    padding: "10px 18px",
    background: "#475569",
    color: "#e2e8f0",
    border: "none",
    borderRadius: 8,
    cursor: "pointer" as const,
    fontWeight: 600,
    fontSize: 14,
  },
  pre: {
    background: "#0f172a",
    padding: 12,
    borderRadius: 6,
    overflow: "auto" as const,
    fontSize: 12,
    maxHeight: 320,
  },
};

function buildRefactorReport(result: SystemScanResult): string {
  const lines: string[] = [
    "# System Refactor Report",
    "",
    "Generated by System Control Center. READ-ONLY — no refactors executed automatically.",
    "",
    "## Totals",
    "",
    "| Metric | Count |",
    "|--------|-------|",
    `| Folders scanned | ${result.totals.foldersScanned} |`,
    `| TSX files | ${result.totals.tsxFiles} |`,
    `| JSON files | ${result.totals.jsonFiles} |`,
    `| Engines detected | ${result.totals.enginesDetected} |`,
    `| Registries | ${result.totals.registries} |`,
    `| Loaders | ${result.totals.loaders} |`,
    `| Runtime modules | ${result.totals.runtimeModules} |`,
    `| UI blocks | ${result.totals.uiBlocks} |`,
    `| Screens | ${result.totals.screens} |`,
    `| Warnings | ${result.totals.warningsCount} |`,
    `| Duplicates | ${result.totals.duplicatesCount} |`,
    `| Legacy paths | ${result.totals.legacyPathsDetected} |`,
    "",
    "## System Structure",
    "",
  ];
  for (const [name, stats] of Object.entries(result.systemStructure)) {
    lines.push(`### ${name}`);
    lines.push(`- Folders: ${stats.folderCount}, Files: ${stats.fileCount}`);
    lines.push(`- Subfolders: ${stats.subfolders.join(", ") || "(none)"}`);
    lines.push("");
  }
  lines.push("## Engines");
  lines.push("");
  result.engines.slice(0, 50).forEach((e) => {
    lines.push(`- **${e.name}** — ${e.location}`);
  });
  if (result.engines.length > 50) lines.push(`- ... and ${result.engines.length - 50} more`);
  lines.push("");
  if (result.blocks) {
    lines.push("## Block System");
    lines.push("");
    lines.push(`- Atoms: ${result.blocks.atomsCount}, Compounds: ${result.blocks.compoundsCount}`);
    lines.push(`- Definition files: ${result.blocks.definitionFilesCount}, Schema files: ${result.blocks.schemaFilesCount}`);
    lines.push(`- Runtime renderers: ${result.blocks.runtimeRenderersCount}`);
    lines.push("");
  }
  lines.push("## Registries");
  lines.push("");
  result.registries.entries.forEach((e) => {
    lines.push(`- ${e.path}${e.duplicated ? " (duplicate)" : ""}`);
  });
  lines.push("");
  lines.push("## Warnings");
  lines.push("");
  result.warnings.forEach((w) => {
    lines.push(`- [${w.severity}] ${w.message}`);
  });
  lines.push("");
  lines.push("## Recommended Fixes");
  lines.push("");
  result.suggestions.forEach((s) => {
    lines.push(`- **${s.area}**: ${s.fix}`);
  });
  return lines.join("\n");
}

function buildCursorCommand(result: SystemScanResult, selectedOptions: Set<ScanOptionKey>): string {
  const areas = Array.from(selectedOptions).map((k) => k.replace("scan", "").replace(/([A-Z])/g, " $1").trim());
  return [
    "Using the findings in src/cursor/SYSTEM_REFACTOR_REPORT.md:",
    "",
    "Target areas: " + (areas.length ? areas.join(", ") : "all") + ".",
    "",
    "Instruct Cursor to:",
    "1. Review the report and suggest fixes only (read-only; do not move files, rename folders, or rewrite imports automatically).",
    "2. Propose step-by-step refactor plans for duplicate registries and legacy paths.",
    "3. Align engine and runtime structure with the documented architecture.",
    "",
    `Current totals: ${result.totals.warningsCount} warnings, ${result.totals.duplicatesCount} duplicates, ${result.totals.legacyPathsDetected} legacy path references.`,
  ].join("\n");
}

function buildAutoRefactorTask(result: SystemScanResult, selectedOptions: Set<ScanOptionKey>): string {
  const areas = Array.from(selectedOptions).length ? Array.from(selectedOptions) : SCAN_OPTIONS.map((o) => o.key);
  return [
    "# Auto Refactor Task",
    "",
    "Generated by System Control Center. Execute manually or via Cursor; no automatic changes.",
    "",
    "## Selected problem areas",
    "",
    ...areas.map((a) => `- ${a}`),
    "",
    "## Step-by-step fix order",
    "",
    "1. **Registries** — Consolidate duplicate registry files; document single source of truth.",
    "2. **Paths** — Update imports from legacy paths (screens/, apps-tsx/core) to current runtime/engine paths.",
    "3. **Engines** — Align engine roots and reduce fragmentation if engines > 20.",
    "4. **Blocks** — Ensure atoms/compounds and definition files match registry usage.",
    "5. **Runtime** — Align runtime/screens, loaders, and registry with app screen loading.",
    "",
    "## Counts (from last scan)",
    "",
    `- Warnings: ${result.totals.warningsCount}`,
    `- Duplicates: ${result.totals.duplicatesCount}`,
    `- Legacy paths: ${result.totals.legacyPathsDetected}`,
    `- Engines: ${result.totals.enginesDetected}`,
    `- Registries: ${result.totals.registries}`,
    "",
    "## Safety",
    "",
    "- Do NOT move files, rename folders, or rewrite imports in this task run unless explicitly requested.",
    "- Scan + report only unless user approves each change.",
  ].join("\n");
}

export default function SystemControlCenter() {
  const [result, setResult] = useState<SystemScanResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<Set<string>>(() => new Set([...SECTION_IDS, "scanControl", "priorityFixes", "miniPlans"] as unknown as string[]));
  const [options, setOptions] = useState<Record<ScanOptionKey, boolean>>(() => {
    const o: Record<string, boolean> = {};
    SCAN_OPTIONS.forEach(({ key }) => {
      o[key] = true;
    });
    return o as Record<ScanOptionKey, boolean>;
  });
  const [reportText, setReportText] = useState("");
  const [taskText, setTaskText] = useState("");
  const [cursorCommand, setCursorCommand] = useState("");
  const [copyStatus, setCopyStatus] = useState<"idle" | "ok" | "fail">("idle");
  const [selectedPlanIds, setSelectedPlanIds] = useState<Set<string>>(new Set());
  const [proposalPanelText, setProposalPanelText] = useState("");
  const [scanModuleSubSelection, setScanModuleSubSelection] = useState<Set<string>>(() => new Set(getAllSubOptionIds()));
  const [completedPlanIds, setCompletedPlanIds] = useState<Set<string>>(new Set());
  const [lastPersisted, setLastPersisted] = useState<{ score: number; ts: number } | null>(null);

  const scanResult = result as SystemScanResult | null;
  const healthScores = useMemo(() => (scanResult ? computeHealthScores(scanResult) : null), [scanResult]);
  const healthBanner = useMemo(() => (scanResult && healthScores ? getHealthBanner(healthScores, scanResult) : null), [scanResult, healthScores]);
  const stabilityScores = useMemo(() => (scanResult ? computeStabilityScores(scanResult) : null), [scanResult]);
  const overallScore = useMemo(() => (stabilityScores ? overallHealthScore(stabilityScores) : null), [stabilityScores]);
  const driftSeverity = useMemo(() => (stabilityScores ? getDriftSeverity(stabilityScores) : null), [stabilityScores]);
  const refactorUrgency = useMemo(() => (stabilityScores && driftSeverity ? getRefactorUrgency(stabilityScores, driftSeverity) : null), [stabilityScores, driftSeverity]);
  const scanCategories = useMemo(() => getScanCategories(scanResult), [scanResult]);
  const safetyZones = useMemo(() => getSafetyZones(scanResult), [scanResult]);
  const prioritySuggestions = useMemo(() => (scanResult ? getPrioritySuggestions(scanResult) : []), [scanResult]);
  const miniPlans = useMemo(() => (scanResult ? getMiniRefactorPlans(scanResult) : []), [scanResult]);
  const selectedPlans = useMemo(() => miniPlans.filter((p) => selectedPlanIds.has(p.id)), [miniPlans, selectedPlanIds]);
  const combinedPlan = useMemo(() => consolidatePlans(selectedPlans), [selectedPlans]);
  const hasHighRiskSelected = selectedPlans.some((p) => p.safetyBadge === "HIGH");

  useEffect(() => {
    const saved = loadControlState();
    if (saved?.lastPlanSelection?.length) {
      setSelectedPlanIds(new Set(saved.lastPlanSelection));
    }
    if (saved?.lastScanTimestamp && saved?.previousHealthScore != null) {
      setLastPersisted({ score: saved.previousHealthScore, ts: saved.lastScanTimestamp });
    }
  }, []);

  useEffect(() => {
    if (selectedPlanIds.size > 0) {
      savePlanSelection(Array.from(selectedPlanIds));
    }
  }, [selectedPlanIds]);

  const togglePlanSelection = (id: string) => {
    setSelectedPlanIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const toggleScanModuleSub = (subId: string) => {
    setScanModuleSubSelection((prev) => {
      const next = new Set(prev);
      if (next.has(subId)) next.delete(subId);
      else next.add(subId);
      return next;
    });
  };

  const markPlanCompleted = (id: string) => {
    setCompletedPlanIds((prev) => new Set(prev).add(id));
  };

  const runScanWithOptions = useCallback(async (scanOptions: Record<ScanOptionKey, boolean>) => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/system-scan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ scanOptions }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error((err as { error?: string }).error || `HTTP ${res.status}`);
      }
      const data = (await res.json()) as SystemScanResult;
      setResult(data);
      const stability = computeStabilityScores(data);
      saveAfterScan(overallHealthScore(stability), stability);
    } catch (e: any) {
      setError(e?.message ?? "Scan failed");
    } finally {
      setLoading(false);
    }
  }, []);

  const runScan = useCallback(() => {
    const scanOptions = SCAN_OPTIONS.reduce<Record<ScanOptionKey, boolean>>((acc, { key }) => {
      acc[key] = options[key];
      return acc;
    }, {} as Record<ScanOptionKey, boolean>);
    runScanWithOptions(scanOptions);
  }, [options, runScanWithOptions]);

  const runSelectedScans = useCallback(() => {
    runScanWithOptions(selectedSubOptionsToApiOptions(scanModuleSubSelection));
  }, [scanModuleSubSelection, runScanWithOptions]);

  const runFullSystemScan = useCallback(() => {
    runScanWithOptions(fullScanApiOptions());
  }, [runScanWithOptions]);

  const copyToClipboard = useCallback(async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopyStatus("ok");
      setTimeout(() => setCopyStatus("idle"), 2000);
    } catch {
      setCopyStatus("fail");
      setTimeout(() => setCopyStatus("idle"), 2000);
    }
  }, []);

  const generateRefactorPlan = useCallback(() => {
    if (!result) return;
    const report = buildRefactorReport(result);
    setReportText(report);
  }, [result]);

  const generateCursorCommand = useCallback(() => {
    if (!result) return;
    const selected = new Set(SCAN_OPTIONS.filter((o) => options[o.key]).map((o) => o.key) as ScanOptionKey[]);
    const text = buildCursorCommand(result, selected);
    setCursorCommand(text);
    copyToClipboard(text);
  }, [result, options, copyToClipboard]);

  const generateTaskFile = useCallback(() => {
    if (!result) return;
    const selected = new Set(SCAN_OPTIONS.filter((o) => options[o.key]).map((o) => o.key) as ScanOptionKey[]);
    setTaskText(buildAutoRefactorTask(result, selected));
  }, [result, options]);

  const generateSelectedPlan = useCallback(() => {
    if (selectedPlans.length === 0) return;
    const proposal = buildRefactorProposal(selectedPlans);
    setProposalPanelText(proposal.markdown);
  }, [selectedPlans]);

  const copyCursorCommandFromPlans = useCallback(() => {
    if (selectedPlans.length === 0) return;
    const proposal = buildRefactorProposal(selectedPlans);
    const text = buildCursorCommandFromProposal(proposal);
    setCursorCommand(text);
    copyToClipboard(text);
  }, [selectedPlans, copyToClipboard]);

  const createTaskFileFromPlans = useCallback(() => {
    if (selectedPlans.length === 0) return;
    const proposal = buildRefactorProposal(selectedPlans);
    setTaskText(buildTaskFileFromProposal(proposal));
  }, [selectedPlans]);

  const toggleSection = (id: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const t = result?.totals;

  return (
    <div style={styles.page}>
      <h1 style={{ fontSize: 24, marginBottom: 8 }}>System Control Center</h1>
      <p style={{ color: "#94a3b8", marginBottom: 24 }}>
        Strategic maintenance console: selectable scans, grouped refactor plans, staged execution. READ-ONLY by default — no engines, renderer, or adapters modified.
      </p>

      {/* Phase 1 — Scan Selection Layer */}
      <div style={styles.section}>
        <div style={styles.sectionHeader} onClick={() => toggleSection("scanControl")}>
          <span>Scan control</span>
          <span>{expanded.has("scanControl") ? "▼" : "▶"}</span>
        </div>
        {expanded.has("scanControl") && (
          <div style={styles.sectionBody}>
            {SCAN_MODULES.map((mod) => (
              <div key={mod.id} style={{ marginBottom: 16 }}>
                <div style={{ fontWeight: 600, marginBottom: 8 }}>{mod.label}</div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                  {mod.subOptions.map((sub) => (
                    <label key={sub.id} style={{ display: "flex", alignItems: "center", gap: 6, cursor: "pointer", fontSize: 13 }}>
                      <input
                        type="checkbox"
                        checked={scanModuleSubSelection.has(sub.id)}
                        onChange={() => toggleScanModuleSub(sub.id)}
                      />
                      {sub.label}
                    </label>
                  ))}
                </div>
              </div>
            ))}
            <div style={{ display: "flex", gap: 12, marginTop: 16 }}>
              <button style={styles.button} onClick={runSelectedScans} disabled={loading}>
                {loading ? "Scanning…" : "Run selected scans"}
              </button>
              <button style={styles.buttonSecondary} onClick={runFullSystemScan} disabled={loading}>
                Run full system scan
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Phase 4 — Stability Scoring */}
      {stabilityScores && overallScore != null && (
        <div style={styles.section}>
          <div style={{ ...styles.sectionHeader, cursor: "default" }}>
            <span>Stability scoring</span>
            <span style={{ fontWeight: 400, fontSize: 14 }}>
              Overall: <strong style={{ color: overallScore >= 70 ? "#22c55e" : overallScore >= 50 ? "#f59e0b" : "#ef4444" }}>{overallScore}</strong>/100
              {driftSeverity != null && ` · Drift: ${driftSeverity}`}
              {refactorUrgency != null && ` · Urgency: ${refactorUrgency}`}
            </span>
          </div>
          <div style={styles.sectionBody}>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))", gap: 12 }}>
              <div>Registry health: <strong>{stabilityScores.registryHealth}</strong></div>
              <div>Identity stability: <strong>{stabilityScores.identityStability}</strong></div>
              <div>Adapter integrity: <strong>{stabilityScores.adapterIntegrity}</strong></div>
              <div>Engine fragmentation: <strong>{stabilityScores.engineFragmentation}</strong></div>
              <div>Legacy debt: <strong>{stabilityScores.legacyDebt}</strong></div>
            </div>
            {lastPersisted && (
              <p style={{ marginTop: 12, fontSize: 12, color: "#94a3b8" }}>
                Last saved score: {lastPersisted.score} ({new Date(lastPersisted.ts).toLocaleString()})
              </p>
            )}
          </div>
        </div>
      )}

      {/* Phase A — System Health Banner */}
      {healthBanner && (
        <div
          style={{
            marginBottom: 24,
            padding: 16,
            borderRadius: 8,
            border: `2px solid ${healthBanner.color}`,
            background: healthBanner.status === "stable" ? "#14532d22" : healthBanner.status === "minor_drift" ? "#42200622" : "#450a0a22",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
            <span style={{ width: 12, height: 12, borderRadius: "50%", background: healthBanner.color }} />
            <strong style={{ fontSize: 16 }}>{healthBanner.label}</strong>
          </div>
          <p style={{ margin: 0, color: "#cbd5e1", fontSize: 14 }}>{healthBanner.explanation}</p>
        </div>
      )}

      {/* Phase E — Scan types breakdown */}
      <div style={styles.section}>
        <div style={styles.sectionHeader} onClick={() => toggleSection("scanBreakdown")}>
          <span>Scan types</span>
          <span>{expanded.has("scanBreakdown") ? "▼" : "▶"}</span>
        </div>
        {expanded.has("scanBreakdown") && (
          <div style={styles.sectionBody}>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}>
              {scanCategories.map((cat) => (
                <div
                  key={cat.id}
                  style={{
                    padding: "8px 12px",
                    background: "#334155",
                    borderRadius: 6,
                    fontSize: 13,
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                  }}
                >
                  <span>
                    {cat.status === "completed" ? "✓" : cat.status === "attention" ? "⚠" : "○"}
                  </span>
                  <span>{cat.label}</span>
                  {cat.summary && <span style={{ color: "#94a3b8" }}>{cat.summary}</span>}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Phase G — Simplified metrics (4 sections) */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: 12, marginBottom: 24 }}>
        <div style={styles.section}>
          <div style={{ ...styles.sectionHeader, cursor: "default" }}><span>Structure</span></div>
          <div style={styles.sectionBody}>
            {t ? (
              <>
                <div>Folders: <strong>{t.foldersScanned}</strong></div>
                <div>TSX: <strong>{t.tsxFiles}</strong></div>
                <div>JSON: <strong>{t.jsonFiles}</strong></div>
                <div>Screens: <strong>{t.screens}</strong></div>
              </>
            ) : (
              <span style={{ color: "#94a3b8" }}>Run scan</span>
            )}
          </div>
        </div>
        <div style={styles.section}>
          <div style={{ ...styles.sectionHeader, cursor: "default" }}><span>Engines</span></div>
          <div style={styles.sectionBody}>
            {t ? (
              <>
                <div>Engines: <strong>{t.enginesDetected}</strong></div>
                <div>Loaders: <strong>{t.loaders}</strong></div>
                <div>Runtime modules: <strong>{t.runtimeModules}</strong></div>
              </>
            ) : (
              <span style={{ color: "#94a3b8" }}>Run scan</span>
            )}
          </div>
        </div>
        <div style={styles.section}>
          <div style={{ ...styles.sectionHeader, cursor: "default" }}><span>Registries</span></div>
          <div style={styles.sectionBody}>
            {t ? (
              <>
                <div>Registries: <strong>{t.registries}</strong></div>
                <div>Duplicates: <strong style={{ color: t.duplicatesCount ? "#f59e0b" : "#22c55e" }}>{t.duplicatesCount}</strong></div>
                <div>Warnings: <strong style={{ color: t.warningsCount ? "#f59e0b" : "#22c55e" }}>{t.warningsCount}</strong></div>
              </>
            ) : (
              <span style={{ color: "#94a3b8" }}>Run scan</span>
            )}
          </div>
        </div>
        <div style={styles.section}>
          <div style={{ ...styles.sectionHeader, cursor: "default" }}><span>UI System</span></div>
          <div style={styles.sectionBody}>
            {t ? (
              <>
                <div>UI blocks: <strong>{t.uiBlocks}</strong></div>
                <div>Legacy paths: <strong style={{ color: t.legacyPathsDetected ? "#f59e0b" : "#22c55e" }}>{t.legacyPathsDetected}</strong></div>
              </>
            ) : (
              <span style={{ color: "#94a3b8" }}>Run scan</span>
            )}
          </div>
        </div>
      </div>

      {/* Phase F — Safety zones */}
      <div style={styles.section}>
        <div style={styles.sectionHeader} onClick={() => toggleSection("safetyZones")}>
          <span>Safety zones (classification only)</span>
          <span>{expanded.has("safetyZones") ? "▼" : "▶"}</span>
        </div>
        {expanded.has("safetyZones") && (
          <div style={styles.sectionBody}>
            {safetyZones.map((zone) => (
              <div key={zone.zone} style={{ marginBottom: 12 }}>
                <div
                  style={{
                    fontWeight: 600,
                    color: zone.zone === "safe" ? "#22c55e" : zone.zone === "caution" ? "#f59e0b" : "#ef4444",
                    marginBottom: 4,
                  }}
                >
                  {zone.label}
                </div>
                <ul style={{ margin: 0, paddingLeft: 20, color: "#94a3b8", fontSize: 13 }}>
                  {zone.items.map((item, i) => (
                    <li key={i}>{item}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Phase 2 — Recommended Refactor Order (plan cards) */}
      {prioritySuggestions.length > 0 && (
        <div style={styles.section}>
          <div style={styles.sectionHeader} onClick={() => toggleSection("priorityFixes")}>
            <span>Recommended refactor order</span>
            <span>{expanded.has("priorityFixes") ? "▼" : "▶"}</span>
          </div>
          {expanded.has("priorityFixes") && (
            <div style={styles.sectionBody}>
              <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                {prioritySuggestions.map((s) => (
                  <div
                    key={s.id}
                    style={{
                      padding: 12,
                      background: completedPlanIds.has(s.id) ? "#14532d22" : "#334155",
                      borderRadius: 8,
                      border: "1px solid #475569",
                    }}
                  >
                    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 8 }}>
                      <strong>{s.title}</strong>
                      <span
                        style={{
                          padding: "2px 8px",
                          borderRadius: 4,
                          fontSize: 11,
                          fontWeight: 600,
                          background: s.safetyBadge === "SAFE" ? "#14532d" : s.safetyBadge === "MEDIUM" ? "#422006" : "#450a0a",
                          color: s.safetyBadge === "SAFE" ? "#86efac" : s.safetyBadge === "MEDIUM" ? "#fcd34d" : "#fca5a5",
                        }}
                      >
                        {s.safetyBadge}
                      </span>
                    </div>
                    <div style={{ color: "#94a3b8", fontSize: 13, marginTop: 4 }}>
                      impact: {s.impact} · safety: {s.safety} · scope: {s.estimatedScope} · affected files: {s.affectedFilesCount}
                    </div>
                    {s.affectedPaths.length > 0 && (
                      <div style={{ fontSize: 12, color: "#64748b", marginTop: 6 }}>
                        {s.affectedPaths.slice(0, 4).join(" · ")}
                        {s.affectedPaths.length > 4 && ` (+${s.affectedPaths.length - 4})`}
                      </div>
                    )}
                    <div style={{ display: "flex", gap: 8, marginTop: 10 }}>
                      <button
                        style={styles.buttonSecondary}
                        onClick={() => setProposalPanelText(`# ${s.title}\n\nAffected: ${s.affectedPaths.slice(0, 8).join("\n")}\n\nScope: ${s.estimatedScope} · Impact: ${s.impact}`)}
                      >
                        Preview plan
                      </button>
                      <button style={styles.buttonSecondary} onClick={() => markPlanCompleted(s.id)}>
                        Mark as completed
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Phase 3 — Combined Refactor Plan */}
      {combinedPlan.planCount > 0 && (
        <div style={styles.section}>
          <div style={styles.sectionHeader} onClick={() => toggleSection("combinedPlan")}>
            <span>Combined refactor plan</span>
            <span>{expanded.has("combinedPlan") ? "▼" : "▶"}</span>
          </div>
          {expanded.has("combinedPlan") && (
            <div style={styles.sectionBody}>
              <div style={{ marginBottom: 12 }}>
                <span
                  style={{
                    padding: "2px 8px",
                    borderRadius: 4,
                    fontSize: 12,
                    fontWeight: 600,
                    background: combinedPlan.estimatedSafety === "SAFE" ? "#14532d" : combinedPlan.estimatedSafety === "MEDIUM" ? "#422006" : "#450a0a",
                    color: combinedPlan.estimatedSafety === "SAFE" ? "#86efac" : combinedPlan.estimatedSafety === "MEDIUM" ? "#fcd34d" : "#fca5a5",
                  }}
                >
                  {combinedPlan.estimatedSafety}
                </span>
                <span style={{ marginLeft: 12, color: "#94a3b8" }}>
                  Estimated impact: {combinedPlan.estimatedRuntimeImpact} · {combinedPlan.planCount} plan(s) · {combinedPlan.affectedPaths.length} path(s)
                </span>
              </div>
              <pre style={styles.pre}>
                {combinedPlan.orderedSteps.join("\n")}
              </pre>
            </div>
          )}
        </div>
      )}

      {/* Phase C — Mini refactor plans (selectable) + Phase 6 safety guard rails */}
      {miniPlans.length > 0 && (
        <div style={styles.section}>
          <div style={styles.sectionHeader} onClick={() => toggleSection("miniPlans")}>
            <span>Mini refactor plans (select 1–10)</span>
            <span>{expanded.has("miniPlans") ? "▼" : "▶"}</span>
          </div>
          {expanded.has("miniPlans") && (
            <div style={styles.sectionBody}>
              {hasHighRiskSelected && (
                <div style={{ padding: 10, background: "#450a0a", borderRadius: 8, marginBottom: 12, color: "#fecaca", fontSize: 13 }}>
                  One or more selected plans are <strong>HIGH</strong> (runtime-touching). Execution buttons are disabled. Use Preview / Copy only.
                </div>
              )}
              {miniPlans.map((plan) => (
                <label
                  key={plan.id}
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: 10,
                    cursor: "pointer",
                    marginBottom: 10,
                    padding: 8,
                    background: selectedPlanIds.has(plan.id) ? "#334155" : "transparent",
                    borderRadius: 6,
                  }}
                >
                  <input
                    type="checkbox"
                    checked={selectedPlanIds.has(plan.id)}
                    onChange={() => togglePlanSelection(plan.id)}
                  />
                  <div style={{ flex: 1 }}>
                    <span style={{ fontWeight: 500 }}>{plan.title}</span>
                    <span
                      style={{
                        marginLeft: 8,
                        padding: "1px 6px",
                        borderRadius: 4,
                        fontSize: 10,
                        fontWeight: 600,
                        background: plan.safetyBadge === "SAFE" ? "#14532d" : plan.safetyBadge === "MEDIUM" ? "#422006" : "#450a0a",
                        color: plan.safetyBadge === "SAFE" ? "#86efac" : plan.safetyBadge === "MEDIUM" ? "#fcd34d" : "#fca5a5",
                      }}
                    >
                      {plan.safetyBadge}
                    </span>
                    <span style={{ color: "#94a3b8", fontSize: 12, marginLeft: 8 }}>
                      impact: {plan.impact} · scope: {plan.scopeSize} · files: {plan.affectedFilesCount}
                    </span>
                  </div>
                </label>
              ))}
              <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 16 }}>
                <button
                  style={styles.button}
                  onClick={generateSelectedPlan}
                  disabled={selectedPlans.length === 0 || hasHighRiskSelected}
                  title={hasHighRiskSelected ? "Disabled: HIGH safety plan selected" : undefined}
                >
                  Generate refactor steps
                </button>
                <button
                  style={styles.buttonSecondary}
                  onClick={copyCursorCommandFromPlans}
                  disabled={selectedPlans.length === 0 || hasHighRiskSelected}
                  title={hasHighRiskSelected ? "Disabled: HIGH safety plan selected" : undefined}
                >
                  Copy Cursor command
                </button>
                <button
                  style={styles.buttonSecondary}
                  onClick={createTaskFileFromPlans}
                  disabled={selectedPlans.length === 0 || hasHighRiskSelected}
                  title={hasHighRiskSelected ? "Disabled: HIGH safety plan selected" : undefined}
                >
                  Create Cursor task file
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Proposal panel (Phase D output) */}
      {proposalPanelText && (
        <div style={styles.section}>
          <div style={styles.sectionHeader} onClick={() => setProposalPanelText("")}>
            <span>Refactor proposal (combined selected plans)</span>
            <span>✕</span>
          </div>
          <div style={styles.sectionBody}>
            <pre style={styles.pre}>{proposalPanelText}</pre>
            <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
              <button style={styles.buttonSecondary} onClick={() => copyToClipboard(proposalPanelText)}>
                Copy
              </button>
              <button
                style={styles.buttonSecondary}
                onClick={() => {
                  const proposal = buildRefactorProposal(selectedPlans);
                  copyToClipboard(buildCursorCommandFromProposal(proposal));
                }}
              >
                Copy as Cursor command
              </button>
              <button
                style={styles.buttonSecondary}
                onClick={() => setTaskText(buildTaskFileFromProposal(buildRefactorProposal(selectedPlans)))}
              >
                Create task file
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Scan options */}
      <div style={styles.section}>
        <div style={styles.sectionHeader} onClick={() => toggleSection("options")}>
          <span>Scan options</span>
          <span>{expanded.has("options") ? "▼" : "▶"}</span>
        </div>
        {expanded.has("options") && (
          <div style={styles.sectionBody}>
            <div style={styles.checkboxRow}>
              {SCAN_OPTIONS.map(({ key, label }) => (
                <label key={key} style={{ display: "flex", alignItems: "center", gap: 6, cursor: "pointer" }}>
                  <input
                    type="checkbox"
                    checked={options[key]}
                    onChange={() => setOptions((o) => ({ ...o, [key]: !o[key] }))}
                  />
                  {label}
                </label>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Action buttons */}
      <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginBottom: 24 }}>
        <button style={styles.button} onClick={runScan} disabled={loading}>
          {loading ? "Scanning…" : "RUN SCAN"}
        </button>
        <button style={styles.buttonSecondary} onClick={generateRefactorPlan} disabled={!result}>
          GENERATE REFACTOR PLAN
        </button>
        <button style={styles.buttonSecondary} onClick={generateCursorCommand} disabled={!result}>
          COPY CURSOR COMMAND
        </button>
        <button style={styles.buttonSecondary} onClick={generateTaskFile} disabled={!result}>
          CREATE NEW CURSOR TASK FILE
        </button>
        {copyStatus === "ok" && <span style={{ color: "#22c55e" }}>Copied.</span>}
        {copyStatus === "fail" && <span style={{ color: "#ef4444" }}>Copy failed.</span>}
      </div>

      {error && (
        <div style={{ padding: 12, background: "#431407", borderRadius: 8, marginBottom: 24, color: "#fecaca" }}>
          {error}
        </div>
      )}

      {/* Report / Cursor command / Task file output */}
      {reportText && (
        <div style={styles.section}>
          <div style={styles.sectionHeader} onClick={() => setReportText("")}>
            <span>SYSTEM_REFACTOR_REPORT.md (copy or download)</span>
            <span>✕</span>
          </div>
          <div style={styles.sectionBody}>
            <pre style={styles.pre}>{reportText}</pre>
            <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
              <button style={styles.buttonSecondary} onClick={() => copyToClipboard(reportText)}>
                Copy to clipboard
              </button>
              <a
                href={`data:text/markdown;charset=utf-8,${encodeURIComponent(reportText)}`}
                download="SYSTEM_REFACTOR_REPORT.md"
                style={styles.buttonSecondary as React.CSSProperties}
              >
                Download SYSTEM_REFACTOR_REPORT.md
              </a>
            </div>
          </div>
        </div>
      )}
      {cursorCommand && (
        <div style={styles.section}>
          <div style={styles.sectionHeader} onClick={() => setCursorCommand("")}>
            <span>Cursor command (paste into chat)</span>
            <span>✕</span>
          </div>
          <div style={styles.sectionBody}>
            <pre style={styles.pre}>{cursorCommand}</pre>
            <button style={styles.buttonSecondary} onClick={() => copyToClipboard(cursorCommand)}>
              Copy to clipboard
            </button>
          </div>
        </div>
      )}
      {taskText && (
        <div style={styles.section}>
          <div style={styles.sectionHeader} onClick={() => setTaskText("")}>
            <span>AUTO_REFACTOR_TASK.md (copy or download)</span>
            <span>✕</span>
          </div>
          <div style={styles.sectionBody}>
            <pre style={styles.pre}>{taskText}</pre>
            <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
              <button style={styles.buttonSecondary} onClick={() => copyToClipboard(taskText)}>
                Copy to clipboard
              </button>
              <a
                href={`data:text/markdown;charset=utf-8,${encodeURIComponent(taskText)}`}
                download="AUTO_REFACTOR_TASK.md"
                style={styles.buttonSecondary as React.CSSProperties}
              >
                Download AUTO_REFACTOR_TASK.md
              </a>
            </div>
          </div>
        </div>
      )}

      {/* Expandable sections */}
      {result && (
        <>
          <div style={styles.section}>
            <div style={styles.sectionHeader} onClick={() => toggleSection("systemStructure")}>
              <span>1) System Structure</span>
              <span>{expanded.has("systemStructure") ? "▼" : "▶"}</span>
            </div>
            {expanded.has("systemStructure") && (
              <div style={styles.sectionBody}>
                {Object.entries(result.systemStructure).map(([name, stats]) => (
                  <div key={name} style={{ marginBottom: 12 }}>
                    <strong>{name}</strong> — folders: {stats.folderCount}, files: {stats.fileCount}
                    <br />
                    <span style={{ color: "#94a3b8", fontSize: 13 }}>Subfolders: {stats.subfolders.join(", ") || "(none)"}</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div style={styles.section}>
            <div style={styles.sectionHeader} onClick={() => toggleSection("engines")}>
              <span>2) Engine Map</span>
              <span>{expanded.has("engines") ? "▼" : "▶"}</span>
            </div>
            {expanded.has("engines") && (
              <div style={styles.sectionBody}>
                <ul style={{ margin: 0, paddingLeft: 20 }}>
                  {result.engines.slice(0, 80).map((e, i) => (
                    <li key={i}>{e.name} — {e.location}</li>
                  ))}
                </ul>
                {result.engines.length > 80 && <p style={{ color: "#94a3b8" }}>… and {result.engines.length - 80} more</p>}
              </div>
            )}
          </div>

          <div style={styles.section}>
            <div style={styles.sectionHeader} onClick={() => toggleSection("blocks")}>
              <span>3) Block System (Atoms / Compounds)</span>
              <span>{expanded.has("blocks") ? "▼" : "▶"}</span>
            </div>
            {expanded.has("blocks") && result.blocks && (
              <div style={styles.sectionBody}>
                <p>Atoms: {result.blocks.atomsCount}, Compounds: {result.blocks.compoundsCount}</p>
                <p>Definition files: {result.blocks.definitionFilesCount}, Schema files: {result.blocks.schemaFilesCount}</p>
                <p>Runtime renderers: {result.blocks.runtimeRenderersCount}</p>
              </div>
            )}
          </div>

          <div style={styles.section}>
            <div style={styles.sectionHeader} onClick={() => toggleSection("registries")}>
              <span>4) Registry Analysis</span>
              <span>{expanded.has("registries") ? "▼" : "▶"}</span>
            </div>
            {expanded.has("registries") && (
              <div style={styles.sectionBody}>
                <p>Total: {result.registries.total}. Duplicated: {result.registries.duplicated.length}</p>
                <ul style={{ margin: 0, paddingLeft: 20 }}>
                  {result.registries.entries.map((e, i) => (
                    <li key={i}>{e.path}{e.duplicated ? " (duplicate)" : ""}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>

          <div style={styles.section}>
            <div style={styles.sectionHeader} onClick={() => toggleSection("runtime")}>
              <span>5) Runtime Structure</span>
              <span>{expanded.has("runtime") ? "▼" : "▶"}</span>
            </div>
            {expanded.has("runtime") && (
              <div style={styles.sectionBody}>
                {result.runtime.map((r, i) => (
                  <div key={i}>{r.path} — {r.fileCount} files. Subfolders: {r.subfolders.join(", ") || "(none)"}</div>
                ))}
              </div>
            )}
          </div>

          <div style={styles.section}>
            <div style={styles.sectionHeader} onClick={() => toggleSection("apps")}>
              <span>6) Apps Structure</span>
              <span>{expanded.has("apps") ? "▼" : "▶"}</span>
            </div>
            {expanded.has("apps") && (
              <div style={styles.sectionBody}>
                <p>Screens: {result.apps.screenCount}, Templates: {result.apps.templateCount}, Generated websites: {result.apps.generatedWebsitesCount}</p>
              </div>
            )}
          </div>

          <div style={styles.section}>
            <div style={styles.sectionHeader} onClick={() => toggleSection("pathHealth")}>
              <span>7) Path Health</span>
              <span>{expanded.has("pathHealth") ? "▼" : "▶"}</span>
            </div>
            {expanded.has("pathHealth") && (
              <div style={styles.sectionBody}>
                {result.pathHealth.length ? (
                  <ul style={{ margin: 0, paddingLeft: 20 }}>
                    {result.pathHealth.map((p, i) => (
                      <li key={i}>{p.kind}: {p.path}{p.root ? ` → ${p.root}` : ""}{p.mismatch ? ` (mismatch: ${p.mismatch})` : ""}</li>
                    ))}
                  </ul>
                ) : (
                  <p style={{ color: "#94a3b8" }}>No path health entries.</p>
                )}
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}
