/**
 * OnboardingGeneratedScreen
 * 
 * Auto-generated wrapper screen for domain: containercreations.com
 * This file is generated by the build-site script.
 * 
 * Thin wrapper that delegates to OnboardingFlowRenderer engine.
 * Contains no hard-coded onboarding content, only the domain reference.
 */

"use client";

import { OnboardingFlowRenderer } from "@/engine/onboarding/OnboardingFlowRenderer";
import { useEffect, useState } from "react";

export default function OnboardingGeneratedScreen() {
  // Domain is hardcoded from folder name
  const domain = "containercreations.com";
  const [flow, setFlow] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    console.log(`[OnboardingGeneratedScreen] Loading onboarding flow for domain: ${domain}`);
    
    fetch(`/api/sites/${domain}/onboarding`)
      .then((res) => {
        if (!res.ok) {
          return res.json().then((errData) => {
            throw new Error(errData.error || errData.message || `Failed to load onboarding: ${res.statusText}`);
          });
        }
        return res.json();
      })
      .then((data) => {
        console.log(`[OnboardingGeneratedScreen] ✓ Onboarding flow loaded from /api/sites/${domain}/onboarding`, data);
        setFlow(data);
        setLoading(false);
        setError(null);
      })
      .catch((err) => {
        console.error("[OnboardingGeneratedScreen] Error loading onboarding:", err);
        setError(err.message || `Failed to load onboarding for domain: ${domain}`);
        setLoading(false);
      });
  }, [domain]);

  if (loading) {
    return (
      <div
        style={{
          minHeight: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontSize: "var(--font-size-lg)",
          color: "var(--color-text-secondary)",
        }}
      >
        Loading onboarding flow...
      </div>
    );
  }

  if (error) {
    return (
      <div
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          padding: "var(--spacing-8)",
          textAlign: "center",
        }}
      >
        <h1
          style={{
            fontSize: "var(--font-size-2xl)",
            fontWeight: "var(--font-weight-bold)",
            marginBottom: "var(--spacing-4)",
            color: "var(--color-text-primary)",
          }}
        >
          Onboarding Flow Not Found
        </h1>
        <p
          style={{
            fontSize: "var(--font-size-base)",
            color: "var(--color-text-secondary)",
            marginBottom: "var(--spacing-4)",
          }}
        >
          {error}
        </p>
        {error.includes("not found") && (
          <p
            style={{
              fontSize: "var(--font-size-sm)",
              color: "var(--color-text-muted)",
              fontFamily: "monospace",
              backgroundColor: "var(--color-bg-secondary)",
              padding: "var(--spacing-4)",
              borderRadius: "var(--radius-md)",
              maxWidth: "600px",
            }}
          >
            Run 'npm run website' for this domain to generate onboarding.flow.json
          </p>
        )}
      </div>
    );
  }

  if (!flow) {
    return (
      <div
        style={{
          minHeight: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontSize: "var(--font-size-lg)",
          color: "var(--color-text-secondary)",
        }}
      >
        No flow data available
      </div>
    );
  }

  return <OnboardingFlowRenderer flow={flow} domain={domain} />;
}
