/**
 * SiteGeneratedScreen
 * 
 * Auto-generated wrapper screen for domain: containercreations.com
 * This file is generated by the build-site script.
 * 
 * Thin wrapper that delegates to GeneratedSiteViewer engine.
 * Contains no hard-coded site content, only the domain reference.
 */

"use client";

import GeneratedSiteViewer from "@/engine/site-runtime/GeneratedSiteViewer";

export default function SiteGeneratedScreen() {
  // Domain is hardcoded from folder name
  const domain = "containercreations.com";
  
  return <GeneratedSiteViewer domain={domain} />;
}
