#!/usr/bin/env ts-node
/**
 * Template Health Scan + Safe Normalization
 * - Scans every template role and reports layoutId/containerWidth sources
 * - Writes TEMPLATE_HEALTH_REPORT.md
 * - Auto-fills missing layoutVariants in template-profiles.json (data only)
 * Does NOT touch spacing, atoms, renderer, or behavior.
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = process.cwd();
const TEMPLATE_PROFILES_PATH = path.resolve(ROOT, "src/04_Presentation/lib-layout/template-profiles.json");
const LAYOUT_DEFINITIONS_PATH = path.resolve(ROOT, "src/04_Presentation/layout/data/layout-definitions.json");
const REPORT_PATH = path.resolve(ROOT, "TEMPLATE_HEALTH_REPORT.md");

type LayoutDefinitions = {
  pageLayouts?: Record<string, { containerWidth?: string; [k: string]: unknown }>;
  templates?: Record<string, Record<string, string>>;
};

type TemplateProfile = {
  id: string;
  sections: Record<string, unknown>;
  layoutVariants?: Record<string, { layoutId: string; containerWidth?: string; params?: Record<string, unknown> }>;
  defaultSectionLayoutId?: string;
  widthByRole?: Record<string, string>;
  containerWidth?: string;
  [k: string]: unknown;
};

type ReportRow = {
  profileId: string;
  role: string;
  layoutId: string;
  layoutSource: "layoutVariant" | "templateRole" | "defaultSection" | "fallback";
  containerWidthSource: string;
};

function loadJson<T>(filePath: string): T {
  const raw = fs.readFileSync(filePath, "utf8");
  return JSON.parse(raw) as T;
}

function resolveLayoutId(
  profile: TemplateProfile,
  role: string,
  layoutDefinitions: LayoutDefinitions
): { layoutId: string; layoutSource: ReportRow["layoutSource"] } {
  const fromVariant = profile.layoutVariants?.[role]?.layoutId?.trim();
  if (fromVariant) return { layoutId: fromVariant, layoutSource: "layoutVariant" };

  const fromTemplates = layoutDefinitions.templates?.[profile.id]?.[role]?.trim();
  if (fromTemplates) return { layoutId: fromTemplates, layoutSource: "templateRole" };

  const fromDefault = profile.defaultSectionLayoutId?.trim();
  if (fromDefault) return { layoutId: fromDefault, layoutSource: "defaultSection" };

  return { layoutId: "content-stack", layoutSource: "fallback" };
}

function resolveContainerWidthSource(
  profile: TemplateProfile,
  role: string,
  layoutId: string,
  layoutDefinitions: LayoutDefinitions
): string {
  const variant = profile.layoutVariants?.[role];
  if (variant?.containerWidth) return "layoutVariant";
  if (profile.widthByRole?.[role]) return "widthByRole";
  const pageLayout = layoutDefinitions.pageLayouts?.[layoutId];
  if (pageLayout?.containerWidth) return "layoutFallback";
  return "rendererFallback";
}

function buildReport(profiles: TemplateProfile[], layoutDefinitions: LayoutDefinitions): ReportRow[] {
  const rows: ReportRow[] = [];
  for (const profile of profiles) {
    const roles = Object.keys(profile.sections ?? {});
    for (const role of roles) {
      const { layoutId, layoutSource } = resolveLayoutId(profile, role, layoutDefinitions);
      const containerWidthSource = resolveContainerWidthSource(
        profile,
        role,
        layoutId,
        layoutDefinitions
      );
      rows.push({
        profileId: profile.id,
        role,
        layoutId,
        layoutSource,
        containerWidthSource,
      });
    }
  }
  return rows;
}

function printTable(rows: ReportRow[]): void {
  const col = (s: string, w: number) => s.padEnd(w).slice(0, w);
  const w = { profileId: 28, role: 14, layoutId: 22, layoutSource: 18, containerWidthSource: 18 };
  console.log("\n" + [col("profileId", w.profileId), col("role", w.role), col("layoutId", w.layoutId), col("layoutSource", w.layoutSource), col("containerWidthSource", w.containerWidthSource)].join(" "));
  console.log("-".repeat(100));
  for (const r of rows) {
    console.log(
      [col(r.profileId, w.profileId), col(r.role, w.role), col(r.layoutId, w.layoutId), col(r.layoutSource, w.layoutSource), col(r.containerWidthSource, w.containerWidthSource)].join(" ")
    );
  }
  console.log("");
}

function writeReportMd(rows: ReportRow[]): void {
  const lines: string[] = [
    "# Template Health Report",
    "",
    "Generated by `scripts/template-health-check.ts`",
    "",
    "| profileId | role | layoutId | layoutSource | containerWidthSource |",
    "|-----------|------|----------|--------------|---------------------|",
  ];
  for (const r of rows) {
    lines.push(`| ${r.profileId} | ${r.role} | ${r.layoutId} | ${r.layoutSource} | ${r.containerWidthSource} |`);
  }
  fs.writeFileSync(REPORT_PATH, lines.join("\n"), "utf8");
  console.log("Report written:", REPORT_PATH);
}

function normalizeProfiles(
  profiles: TemplateProfile[],
  layoutDefinitions: LayoutDefinitions
): { profiles: TemplateProfile[]; rolesAdded: number; containerWidthsFilled: number; profilesTouched: number } {
  let rolesAdded = 0;
  let containerWidthsFilled = 0;
  const profilesTouchedSet = new Set<string>();

  for (const profile of profiles) {
    const roles = Object.keys(profile.sections ?? {});
    let profileTouched = false;

    for (const role of roles) {
      // Ensure layoutVariants exists
      if (!profile.layoutVariants) {
        profile.layoutVariants = {};
      }

      if (!profile.layoutVariants[role]) {
        const layoutId =
          layoutDefinitions.templates?.[profile.id]?.[role]?.trim() ??
          profile.defaultSectionLayoutId?.trim() ??
          "content-stack";
        profile.layoutVariants[role] = { layoutId };
        rolesAdded++;
        profileTouched = true;
      } else {
        // layoutVariants[role] exists but containerWidth missing AND profile.widthByRole[role] exists
        const variant = profile.layoutVariants[role];
        if (variant.containerWidth === undefined && profile.widthByRole?.[role]) {
          variant.containerWidth = profile.widthByRole[role];
          containerWidthsFilled++;
          profileTouched = true;
        }
      }
    }

    if (profileTouched) profilesTouchedSet.add(profile.id);
  }

  return {
    profiles,
    rolesAdded,
    containerWidthsFilled,
    profilesTouched: profilesTouchedSet.size,
  };
}

function main(): void {
  console.log("[template-health-check] Loading template-profiles and layout-definitions...");

  const layoutDefinitions = loadJson<LayoutDefinitions>(LAYOUT_DEFINITIONS_PATH);
  const validLayoutIds = Object.keys(layoutDefinitions.pageLayouts ?? {});
  console.log("Valid layout IDs:", validLayoutIds.length);

  const profiles = loadJson<TemplateProfile[]>(TEMPLATE_PROFILES_PATH);
  console.log("Profiles:", profiles.length);

  // Step 1 — Scan and report
  const rows = buildReport(profiles, layoutDefinitions);
  console.log("\n--- Template health table ---");
  printTable(rows);
  writeReportMd(rows);

  // Step 2 — Safe auto-normalize (mutate profiles in memory, then write back)
  const result = normalizeProfiles(profiles, layoutDefinitions);

  fs.writeFileSync(
    TEMPLATE_PROFILES_PATH,
    JSON.stringify(profiles, null, 2),
    "utf8"
  );
  console.log("Updated", TEMPLATE_PROFILES_PATH);

  // Step 3 — Summary
  console.log("\nTemplates normalized:");
  console.log("  - roles added:", result.rolesAdded);
  console.log("  - containerWidths filled:", result.containerWidthsFilled);
  console.log("  - profiles touched count:", result.profilesTouched);
}

main();
