/**
 * verify-compounds-manifest.ts
 * Reads src/blocks/compounds.manifest.json and scans src/compounds/ui/12-molecules/*.compound.tsx.
 * Compares count + id match; outputs src/cursor/COMPOUNDS_MANIFEST_VERIFICATION_REPORT.md
 * with: compound id, runtime file exists? YES/NO, missing in manifest?, missing on disk?
 * NO CHANGES to runtime.
 */

import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const MANIFEST_PATH = path.join(ROOT, "src/blocks/compounds.manifest.json");
const RUNTIME_DIR = path.join(ROOT, "src/compounds/ui/12-molecules");
const REPORT_PATH = path.join(ROOT, "src/cursor/COMPOUNDS_MANIFEST_VERIFICATION_REPORT.md");

function loadJson(filePath: string): unknown {
  const raw = fs.readFileSync(filePath, "utf-8");
  return JSON.parse(raw);
}

/** runtimePath like @/compounds/ui/12-molecules/section.compound -> expected file section.compound.tsx */
function runtimePathToFileName(runtimePath: string): string {
  const base = path.basename(runtimePath.replace(/^@\//, ""));
  return base.endsWith(".tsx") ? base : `${base}.tsx`;
}

/** *.compound.tsx file name -> compound id (e.g. section.compound.tsx -> section) */
function fileNameToId(fileName: string): string {
  return fileName.replace(/\.compound\.tsx$/, "");
}

function main() {
  const manifest = loadJson(MANIFEST_PATH) as {
    compounds: Record<string, { id: string; runtimePath?: string }>;
  };
  const compounds = manifest?.compounds ?? {};
  const manifestIds = Object.keys(compounds);

  const runtimeFiles = fs.existsSync(RUNTIME_DIR)
    ? fs.readdirSync(RUNTIME_DIR).filter((f) => f.endsWith(".compound.tsx"))
    : [];
  const diskIds = runtimeFiles.map(fileNameToId);

  const rows: {
    id: string;
    source: "manifest" | "disk" | "both";
    runtimeFileExists: string;
    missingInManifest: "YES" | "NO";
    missingOnDisk: "YES" | "NO";
  }[] = [];

  const allIds = new Set([...manifestIds, ...diskIds]);

  for (const id of [...allIds].sort()) {
    const inManifest = manifestIds.includes(id);
    const inDisk = diskIds.includes(id);
    const entry = compounds[id];
    const expectedFile = entry?.runtimePath
      ? runtimePathToFileName(entry.runtimePath)
      : `${id}.compound.tsx`;
    const runtimeFilePath = path.join(RUNTIME_DIR, expectedFile);
    const runtimeFileExists = inManifest
      ? fs.existsSync(runtimeFilePath)
        ? "YES"
        : "NO"
      : "—";

    rows.push({
      id,
      source: inManifest && inDisk ? "both" : inManifest ? "manifest" : "disk",
      runtimeFileExists,
      missingInManifest: inManifest ? "NO" : "YES",
      missingOnDisk: inDisk ? "NO" : "YES",
    });
  }

  const reportLines: string[] = [
    "# Compounds Manifest Verification Report",
    "",
    "Generated by `scripts/verify-compounds-manifest.ts`",
    "",
    "## Summary",
    "",
    `- Manifest: \`src/blocks/compounds.manifest.json\``,
    `- Runtime: \`src/compounds/ui/12-molecules/*.compound.tsx\``,
    `- Compound ids in manifest: ${manifestIds.length}`,
    `- Compound TSX files on disk: ${runtimeFiles.length}`,
    `- Ids in both: ${rows.filter((r) => r.source === "both").length}`,
    `- Missing in manifest: ${rows.filter((r) => r.missingInManifest === "YES").length}`,
    `- Missing on disk: ${rows.filter((r) => r.missingOnDisk === "YES").length}`,
    "",
    "## Per-compound",
    "",
    "| Compound id | Runtime file exists? | Missing in manifest? | Missing on disk? |",
    "|-------------|----------------------|----------------------|-----------------|",
  ];

  for (const r of rows) {
    reportLines.push(`| ${r.id} | ${r.runtimeFileExists} | ${r.missingInManifest} | ${r.missingOnDisk} |`);
  }

  reportLines.push("");

  const reportDir = path.dirname(REPORT_PATH);
  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }
  fs.writeFileSync(REPORT_PATH, reportLines.join("\n"), "utf-8");
  console.log("Report written to", REPORT_PATH);
}

main();
