/**
 * verify-compounds-manifest.ts
 * Scans src/components/molecules/*.compound.tsx (12 contract molecules).
 * Outputs src/cursor/COMPOUNDS_MANIFEST_VERIFICATION_REPORT.md with molecule id and file existence.
 * NO CHANGES to runtime.
 */

import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const RUNTIME_DIR = path.join(ROOT, "src/components/molecules");
const REPORT_PATH = path.join(ROOT, "src/cursor/COMPOUNDS_MANIFEST_VERIFICATION_REPORT.md");

/** *.compound.tsx file name -> molecule id (e.g. section.compound.tsx -> section) */
function fileNameToId(fileName: string): string {
  return fileName.replace(/\.compound\.tsx$/, "");
}

function main() {
  const runtimeFiles = fs.existsSync(RUNTIME_DIR)
    ? fs.readdirSync(RUNTIME_DIR).filter((f) => f.endsWith(".compound.tsx")).sort()
    : [];
  const diskIds = runtimeFiles.map(fileNameToId);

  const rows: { id: string; runtimeFileExists: "YES" | "NO" }[] = diskIds.map((id) => ({
    id,
    runtimeFileExists: "YES" as const,
  }));

  const reportLines: string[] = [
    "# Molecules (Compounds) Verification Report",
    "",
    "Generated by `scripts/verify-compounds-manifest.ts`",
    "",
    "## Summary",
    "",
    `- Runtime: \`src/components/molecules/*.compound.tsx\``,
    `- Molecule TSX files on disk: ${runtimeFiles.length}`,
    "",
    "## Per-molecule",
    "",
    "| Molecule id | Runtime file exists? |",
    "|-------------|----------------------|----------------------|-----------------|",
  ];

  for (const r of rows) {
    reportLines.push(`| ${r.id} | ${r.runtimeFileExists} |`);
  }

  reportLines.push("");

  const reportDir = path.dirname(REPORT_PATH);
  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }
  fs.writeFileSync(REPORT_PATH, reportLines.join("\n"), "utf-8");
  console.log("Report written to", REPORT_PATH);
}

main();
